# Generated by Django 3.0.5 on 2020-05-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
